blank_issues_enabled: false
contact_links:
  - name: GitHub discussions
    url: https://github.com/d10n/agg-plus/discussions
    about: Ideas, feature requests, help requests, questions and general discussions should be posted here.
